---
asn: 65511
rid: 1.1.1.1
neighbors:
  - ipaddr: 10.10.12.2
    remote_asn: 65512
  - ipaddr: 10.10.13.3
    remote_asn: 65513
interfaces:
  GigabitEthernet4:
    ipaddr: 10.10.12.1
    mask: 255.255.255.252
    description: Link to csr2
    state: up
  GigabitEthernet2:
    ipaddr: 10.10.13.1
    mask: 255.255.255.248
    description: Link to csr3
    state: up
