---

- name: Validate BGP Playbook
  hosts: routers
  gather_facts: no
  connection: local

  vars:
    provider:
      username: "{{ansible_user}}"
      password: "{{ansible_password}}"
      host: "{{inventory_hostname}}"

  tasks:
    - name: Napalm validate bgp
      napalm_validate:
        validation_file: templates/validation/{{inventory_hostname}}_bgp.yaml
      register: validate_bgp

    - name: Validate BGP complies using NAPALM validate
      fail:
        msg: Not in compliance with validation file
      when: not validate_bgp.compliance_report.complies