---
asn: 65513
rid: 3.3.3.3
neighbors:
  - ipaddr: 10.10.13.1
    remote_asn: 65511
  - ipaddr: 10.10.23.2
    remote_asn: 65512
interfaces:
  GigabitEthernet2:
    ipaddr: 10.10.13.3
    mask: 255.255.255.248
    description: Link to csr1
    state: up
  GigabitEthernet3:
    ipaddr: 10.10.23.3
    mask: 255.255.255.248
    description: Link to csr2
    state: up
